config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'posts#index'
  devise_for :users
  resources :posts
  resources :users
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post


  	# after_save :add_score

  	# private

  	# def add_score
   # 	 	self.user.score += 10
   #  	self.user.save
 	 # end
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments



	has_attached_file :image,
                    styles: { :medium => "300x300" },
                    default_url: '/images/:style/missing.png'
  	validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']

end

app/models/user.rb
class User < ApplicationRecord
	 has_many :posts
	 has_many :comments, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password )}
   	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
	  @posts = Post.all
	  @comment = Comment.new
	end

 	def create
  		@post = Post.find(params[:comment][:post_id])
  		@comment = @post.comments.build(comment_params)
  		@comment.user_id = current_user.id
	  	if @comment.save	
	  		# current_user.score += 10
  			# current_user.save  	
		 	redirect_to root_url
		end
	end
  
  	def destroy
        @post = Post.find_by(params[:id])
        @comment = Comment.find_by(params[:id])
        @comment.destroy
        redirect_to users_path
    end


	private

	def comment_params
		params.require(:comment).permit(:content, :post_id, :user_id)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
  	@post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def index
  	@posts = Post.all.order(created_at: :DESC)
     @comments = Comment.all
    
  end

  def create
  	@post = Post.create(post_params)
  	if @post.save	 
  		redirect_to root_url
  	else	 
  		render 'new'
  	end
  	
  end
  private
  def post_params
    params.require(:post).permit(:image, :user_id, :comment_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  	@posts = Post.all
    @post = Post.new
  end

  def destroy
  	@post = Post.destroy(params[:id])
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="user-name "> 
    <%= comment.user.name %>
</div>
  <div class="comment-content">
   		 <%= comment.content %>
   		 <div class="text-right">
			  <%if current_user == comment.user %>
			    <p class="comment-delete"><%= link_to comment_path(comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
     				<%end%>
     				</p>
 				<%end%>
  		</div>
  </div>

app/views/comments/_form.html.erb
<div class="comment-form col-sm-11">
	<%= form_for [post.comments.build], html: { class: 'form-horizontal'} do |f| %>
		<%= f.hidden_field  :post_id,  value: post.id%>
		<%= f.text_area :content ,placeholder: "write comment",class:"comment_content", id: "comment_content_#{post.id}"%>
		<%= f.submit  class: 'btn-success' %>
		<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <nav class="navbar  navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Gallery', root_path, class: 'navbar-brand' %>
            <%= link_to 'Admin', admin_root_path, class: 'navbar-brand' %> 
          </div>

          <div class="collapse navbar-collapse" id="navbar-collapse">
            
            <ul class="navbar-nav navbar-right">
              <% if user_signed_in? %>
                <p class="navbar-text">
                  Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
                </p>
                <li><%= link_to 'My Profile', users_path, class: 'navbar-brand' %></li> 
                <li><%= link_to 'New Post', new_post_path, class: 'navbar-brand' %></li> 
                 

                
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                      <li><a href="#">View orders</a></li>
                      <li class="divider"></li>
                      <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                    </ul>
                  </li>
                </ul>
              <% else %>
                <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
                <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="conrainer">
     
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { class: 'form-horizontal'} do |f| %>
	<div class="form-group text-center">
		<h4>New Post</h4>
			 <%=  f.file_field :image %>	
			 <%=  f.label :description %>
			 <%=  f.text_area :description %>
			 <%=  f.hidden_field :user_id, :value => current_user.id %>
		   <div class="form-group text-center">
	     <%= f.submit  class: 'btn-success' %>
		</div>	
	 </div>	
	</div>
<% end%>	
	

app/views/posts/index.html.erb
<div class="conrainer">
    <% @posts.each do |post| %>
      <div class="col-xs-6 col-sm-4"> 
          <b><%= post.user.name %></b>       
          <%= image_tag  post.image.url(:medium), class:'img-responsive' %>
          <%= post.description  %>
          <%= render post.comments ,post: post %> 
          <% if user_signed_in? %>
            <%= render 'comments/form', post: post %>  
          <% end %>
          <div class="img" style="background-image: url('<%= image_path post.image.url(:medium) %>');"></div>         
      </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
	<% @posts = Post.all %>
	<% current_user.posts.each do |post| %> 
	  	<div class="col-xs-6 col-sm-4"> 
	        <%= image_tag  post.image.url(:medium), class:'img-responsive' %>  
	      <br>  
	      <div class="des">   
	        <%= post.description %>
	      </div>
	        <% post.comments.each do |comment| %>
	        <b><%= comment.user.name %> </b> 
	        <div class="comment">
	          <p><%= comment.content %></p>
	        </div> 
	         <% if current_user == post.user %>
	              <%= link_to 'Delete comment',  comment_path(comment), class: 'btn btn-success',
	                        method: :delete, 
	                        data: {confirm: 'Do you want to remove this post?'} %> 
			                 
	         <% else %>
	          <% redirect_to user_path %>                    
	          <% end %>
	        <% end %>
	        <%= link_to 'Delete',  user_url(post), class: 'btn btn-success',
	                        method: :delete,
	                        data: {confirm: 'Do you want to remove this post?'} %>   
	   	</div> 
	<% end %>
</div>